### your site title here
title: Akshay Kale
description: Ph.D. Candidate | University of Nebraska | Artificial Intelligence

baseurl: /ak-blog #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: akshaykale4@icloud.com

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
facebook: "#"
twitter: "KaleNotTheSalad"
linkedin: "#"
github: "kaleoyster"
researchgate: "Akshay-Kale-2"
googlescholar: "nmE-DNUAAAAJ&hl=en&oi=sra"
orcid: "0000-0001-6191-7996"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Collection
collections:
  projects:
    output: false
    permalink: /projects/:path/
  resumes:
    output: false
    permalink: /resumes/:path/
  drafts:
    output: false
    permalink: /drafts/:path/
  research:
    output: false
    permalink: /projects/:path/


sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
